region          = "us-west-2"
billing_mode    = "PAY_PER_REQUEST"
hash_key        = "LockID"
attribute_name  = "LockID"
attribute_type  = "S"

owner                            = "techiescamp"
environment                      = "dev"
cost_center                      = "techiescamp-commerce"
application                      = "java-app"